private static final Logger logger = LogManager.getLogger("a_Edge");

// Inner class for vertex points
public static class VertexPoint {
    public double x, y, z;
    
    public VertexPoint(double x, double y, double z) {
        this.x = x;
        this.y = y;
        this.z = z;
    }
}

// IDataDriver methods are auto-generated by AnyLogic from the interface
// Logger available for debugging: logger.info(), logger.error(), etc.
