private static final Logger logger = LogManager.getLogger("a_Vertex");

// IDataDriver methods are auto-generated by AnyLogic from the interface
// Logger available for debugging: logger.info(), logger.error(), etc.